public class Fetchconrecords {
  /*   @AuraEnabled(cacheable=true) 
    Public static list<contact>getrecords(){
         return [SELECT Id, LastName, Email,FirstName FROM contact limit 10 ];
        
      }  
        @AuraEnabled
        Public static string updateconrecord(object condata){
            
        System.debug('condata:'+condata);
           List<contact>conreclist = (list<contact>) JSON.deserialize(
               JSON.Serialize(condata),List<account>class);
            If(!conreclist.isEmpty)()){
                update conreclist;
                return 'success';
            }
            return 'Failed';
  
    }*/
}